### ISSUE TITLE
memory efficiency

### ISSUE THREAD

**Issue by ptrab** [jensengroup/take_elementary_step#1]
Hi,

I was just playing around with a little bit bigger system (20 non-H) than formic acid or the small diels alder and as while tes.take_elementary_step() runs, my memory is filled from 20 to 100% in about 10 seconds.

Could it be done that not all possible steps are generated and then saved but that each step is saved on its own? Or maybe with little batches of 5 TES or so.

Thanks
Philipp

**Comment by jhjensen2** [comment]
Hi Philipp

yes, I am also starting to realise that memory is a problem for all but the smallest systems.

I think perhaps the solution is to change get_C such that the intermediates, I, are made right away and only stored if they are valid (I_is_valid).  I hope to test this soon.

Best regards, Jan

**Comment by jhjensen2** [comment]
I've implemented my idea and it seems to solve the problem.  Give it a try. If it doesn't solve your problem open another issue
