### ISSUE TITLE
Add chirality to take elementary step

### ISSUE THREAD

**Issue by laestis** [jensengroup/take_elementary_step#2]
Hi,

I noticed tthe script does not take into account the explicit chirality of an inputed smiles (if I input a chiral smiles, the output will be the same achiral smiles than with an achiral input).
Would it be possible to add a chirality criteria to the slementary stepper?

Best

**Comment by jhjensen2** [comment]
If I understand correctly, what you request is a feature where if a chiral center is unchanged and the center is still chiral in the output smile then the chirality should be preserved?  If bonds to the chiral center are changed then I don't see a way to predict the correct chirality in the product.

It would help if you could provide me with a use case: i.e. a chiral input smiles and examples of chiral and achiral products you would like to see.

**Comment by jhjensen2** [comment]
Should work now. If not open another issue on github
